### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by mimmi20** [mimmi20/browscap-helper-source-detector#10]
[warning] E_WARNING: Invalid argument supplied for foreach()
PHP Warning:  Invalid argument supplied for foreach() in /home/developer/projects/browscap-helper/vendor/mimmi20/browscap-helper-source-detector/src/DetectorSource.php on line 115

**Comment by bigpurplebox** [comment]
is this the same issue as the following : Warning: Invalid argument supplied for foreach() in /homepages/5/d689645716/htdocs/clickandbuilds/InspireMeEquestrian/wp-content/plugins/unyson/framework/helpers/general.php on line 1258

**Comment by mimmi20** [comment]
no
