### ISSUE TITLE
Error after updating to the latest version - Version 2.7.6

### ISSUE THREAD

**Issue by bigpurplebox** [mimmi20/browscap-helper-source-detector#12]
Warning: Invalid argument supplied for foreach() in /homepages/5/d689645716/htdocs/clickandbuilds/InspireMeEquestrian/wp-content/plugins/unyson/framework/helpers/general.php on line 1258

**Comment by mimmi20** [comment]
wrong project?

**Comment by bigpurplebox** [comment]
I don't believe it's the wrong project the error is in the Unyson Plugin, it only appeared after the update to 2.7.6

**Comment by mimmi20** [comment]
This project is not for any WP plugin.
